# Generated by Django 2.2.11 on 2020-04-29 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipe_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
